services:
  app:
    image: 'jc21/nginx-proxy-manager:2.13.7'
    restart: unless-stopped
    ports:
      - '80:80'      # HTTP Traffic
      - '81:81'      # Admin Interface
      - '443:443'    # HTTPS Traffic
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - reverse_proxy_net

networks:
  proxy_net:
    name: reverse_proxy_net
    driver: bridge
